on: 
  push:
    paths-ignore:
      - "README.md"
      - "**.json"
      - "action.yml"
  workflow_dispatch:

jobs:
  veracode-sandbox-task:
    runs-on: ubuntu-latest
    name: Clean 2 Sandboxes

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Sandbox Cleaning
        env:
          VERACODE_API_ID: '${{ secrets.VERACODE_API_ID }}'
          VERACODE_API_SECRET: '${{ secrets.VERACODE_API_SECRET }}'
        uses: ./
        with:
          activity: "promote-latest-scan"
          app-name: "Verademo-Brances"
          sandbox-name: "test-01"
          delete-on-promote: true
          # clean-amount: "2" # (Optional) Number - with default as 1
