on: [push,workflow_dispatch]

jobs:
  veracode-sandbox-task:
    runs-on: ubuntu-latest
    name: Clean 2 Sandboxes

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Sandbox Cleaning
        env:
          VERACODE_API_ID: '${{ secrets.VERACODE_API_ID }}'
          VERACODE_API_SECRET: '${{ secrets.VERACODE_API_KEY }}'
        uses: ./
        with:
          activity: "remove-sandbox"
          app-name: "My Application"
          clean-amount: "2" # (Optional) Number - with default as 1