on: 
  workflow_dispatch:

jobs:
  veracode-sandbox-task:
    runs-on: ubuntu-latest
    name: Clean 2 Sandboxes

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Sandbox Cleaning
        env:
          VERACODE_API_ID: '${{ secrets.VERACODE_API_ID }}'
          VERACODE_API_SECRET: '${{ secrets.VERACODE_API_SECRET }}'
        uses: ./
        with:
          activity: "clean"
          app-name: "Verademo-Brances"
          clean-amount: "2" 
          
